# Reinforcement Learning - Markov를 활용한 Path Finding
15개의 state가 있는 grid world에서 각 위치마다 어떤 행동(up down left right)을 해야 보상을 많이 받는지 찾는 코드

## 1. P : Transition Probability Matrix
현재 state에서 어떤 action을 했을 때 다음 state로 갈 확률

In [1]:
import numpy as np

P = np.array([
    # up
    # 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
     ],
    # down
    # 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
    [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
     ],
    # left
    # 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
     ],
    # right
    # 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15
    [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
     ]
], dtype='float32')

In [2]:
P = P.transpose(1, 0, 2)

In [8]:
P.shape

(15, 4, 15)

### 15개의 State, 4개의 Action, 15개의 next state

## 2. R : Reward

In [3]:
R = np.array([
    [-1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0], # up
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, 0], # down
    [ 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0],
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, 0]
])

In [4]:
R = R.transpose()

## 3. pi : Policy
각 state에서 up/down/left/right를 선택할 확률

In [5]:
pi = np.ones((15, 4), dtype='float32') * 0.25

## 4. Policy Iteration (Evaluation & Improvement)
policy_eval : Evaluation : 각 state의 value를 계산함. V(s) = 현재 state s에서 시작했을 때 앞으로 받을 보상의 기대값 (Bellman Expectation 사용)

policy_upd : Improvement : 현재 value v를 기준으로 각 state에서 가장 좋은 action을 고름. (각 state마다 Q-value가 가장 큰 action의 index를 고름)

그리고 while loop 안에서
1. 현재 policy pi를 평가해서 V(s)를 구함
2. V(s)를 이용해 더 좋은 policy로 업데이트함
3. policy가 더 이상 바뀌지 않으면 종료

In [6]:
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 15), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    print(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )))
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((15, 4), dtype='float32')
    pi[range(15), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((15, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

[[-1.81250876 -2.25813198  1.         -2.346084  ]
 [-2.346084   -2.38126493 -1.81250876 -2.43403602]
 [-2.43403602 -2.346084   -2.346084   -2.43403602]
 [ 1.         -2.346084   -1.81250876 -2.25813198]
 [-1.81250876 -2.38126493 -1.81250876 -2.38126493]
 [-2.346084   -2.25813198 -2.25813198 -2.346084  ]
 [-2.43403602 -1.81250876 -2.38126493 -2.346084  ]
 [-1.81250876 -2.43403602 -2.346084   -2.38126493]
 [-2.25813198 -2.346084   -2.346084   -2.25813198]
 [-2.38126493 -1.81250876 -2.38126493 -1.81250876]
 [-2.346084    1.         -2.25813198 -1.81250876]
 [-2.346084   -2.43403602 -2.43403602 -2.346084  ]
 [-2.38126493 -2.346084   -2.43403602 -1.81250876]
 [-2.25813198 -1.81250876 -2.346084    1.        ]
 [ 0.          0.          0.          0.        ]]
[[-0.39999998 -1.23999999  1.         -1.23999999]
 [-1.23999999 -1.74400002 -0.39999998 -1.74400002]
 [-1.74400002 -1.23999999 -1.23999999 -1.74400002]
 [ 1.         -1.23999999 -0.39999998 -1.23999999]
 [-0.39999998 -1.74400002 -0.3

In [7]:
print(pi)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


# each row = each state
# each column = each action

[0, 0, 0, 1] : go right

[1, 0, 0, 0] : go up